name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install Dependencies
        run: sudo apt-get install -y ninja-build cmake gcovr

      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Build
        run: |
          cmake -GNinja -Bbuild -DCMAKE_BUILD_TYPE=Debug
          ninja -C build

      - name: Test
        run: build/ring_buffer

      - name: Generate Coverage Report
        run: gcov build/CMakeFiles/ring_buffer.dir/src/ring_buffer.c.gcno

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: 'ring_buffer.c.gcov'